# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Headers for Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://firebasestorage.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://*.firebaseio.com https://*.cloudfunctions.net https://*.googleapis.com wss://*.firebaseio.com;"